version: '3'

services:
  
  keycloak:
      build: .
      environment:
        - DB_VENDOR=POSTGRES
        - DB_ADDR=postgres
        - DB_DATABASE=keycloak
        - DB_USER=keycloak
        - DB_SCHEMA=public
        - DB_PASSWORD=password
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=admin
        - KCBASE=/opt/jboss/keycloak/
        - PROXY_ADDRESS_FORWARDING=true
      ports:
        - 8080:8080
      depends_on:
        - hs-auth-server
        - postgres

  keycloak-db:
    image: postgres:10
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloakdb
    volumes:
      - pgdata1:/var/lib/postgresql/data

volumes:
  pgdata1: