version: '3'

volumes:
  postgresdatabase2:
      driver: local  

services:
  postgres:
      image: postgres:10
      volumes:
        - postgresdatabase2:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports:
        - 5432:5432

  keycloak:
      image: jboss/keycloak:4.8.3.Final
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        KCBASE: /opt/jboss/keycloak/
      ports:
        - 8080:8080
      depends_on:
        - postgres

  hs-auth-server:
      image: hypermine/hs-auth-server
      ports:
        - 3000:3000
        


        